name: Docker Base Image Builds

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main
      - dev

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  IMAGE: ghcr.io/k-e-n-w-a-y/aria-telegram-mirror-bot

jobs:
  build:
    name: BuildDockerImage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - if: github.event.pusher.name != 'k-e-n-w-a-y'
        name: Check last commit author
        run: echo "Author mismatch existing..." && exit 1

      - name: Login to ghcr.io registry
        run: docker login https://ghcr.io -u token -p ${{ secrets.GH_TOKEN }}

      - name: Build and Push image
        run: |
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          echo VERSION=$VERSION
          echo "Building"
          docker build . -f docker-publish/Dockerfile -t ${{ env.IMAGE }}:$VERSION
          [ "$VERSION" == "main" ] && docker tag ${{ env.IMAGE }}:$VERSION ${{ env.IMAGE }}:latest
          echo "Pushing"
          docker push --all-tags ${{ env.IMAGE }}